# Generated by Django 3.0.2 on 2022-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('meeting_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-meeting_count'],
            },
        ),
    ]
